#!/bin/sh
PR1=vpn-proxy1
port1=6001
chmod +x up.sh
chmod +x down.sh
apt-get install socat -y
socat TCP-LISTEN:6002,fork TCP:127.0.0.1:$port1 &
docker rmi $PR1
docker rm $PR1 --force
docker build -t $PR1 .
exec docker run \
    --name=$PR1 \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --cap-add=NET_ADMIN \
    --publish 127.0.0.1:$port1:1080 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    $PR1

